### ISSUE TITLE
Assertation error

### ISSUE THREAD

**Issue by muuvmuuv** [additive/bulk-optimization#1]
Might be something with greenlet.

```
Processing file 166 of 289
>>> /Users/marvinheilemann/Desktop/Origin_Screencasts_cleared/Minitools-VertikalerCursor/Minitools-VertikalerCursor.mp4
<<< /Users/marvinheilemann/Desktop/Origin_Screencasts_cleared-copy/Minitools-VertikalerCursor/Minitools-VertikalerCursor…
[INFO] [video] Filename: Minitools-VertikalerCursor.mp4
[INFO] [video] Filesize: 6.6 MB
[NEXT] [video] [mp4] Starting compression...
  0%|                                                                                                                                                  | 0/162.05 [00:00<?, ?it/s]Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/Users/marvinheilemann/Development/Scripts/Bulk Video Converter/utils/progress.py", line 40, in _do_watch_progress
    handler(key, value)
  File "/Users/marvinheilemann/Development/Scripts/Bulk Video Converter/utils/progress.py", line 85, in handler
    bar.update(time - bar.n)
  File "/Users/marvinheilemann/Development/Scripts/Bulk Video Converter/venv/lib/python3.7/site-packages/tqdm/std.py", line 1200, in update
    self.refresh(lock_args=self.lock_args)
  File "/Users/marvinheilemann/Development/Scripts/Bulk Video Converter/venv/lib/python3.7/site-packages/tqdm/std.py", line 1304, in refresh
    self.display()
  File "/Users/marvinheilemann/Development/Scripts/Bulk Video Converter/venv/lib/python3.7/site-packages/tqdm/std.py", line 1428, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/Users/marvinheilemann/Development/Scripts/Bulk Video Converter/venv/lib/python3.7/site-packages/tqdm/std.py", line 1058, in __repr__
    return self.format_meter(**self.format_dict)
  File "/Users/marvinheilemann/Development/Scripts/Bulk Video Converter/venv/lib/python3.7/site-packages/tqdm/std.py", line 482, in format_meter
    charset=Bar.ASCII if ascii is True else ascii or Bar.UTF)
  File "/Users/marvinheilemann/Development/Scripts/Bulk Video Converter/venv/lib/python3.7/site-packages/tqdm/std.py", line 146, in __init__
    assert 0 <= frac <= 1
AssertionError
2019-12-04T12:28:29Z <Greenlet at 0x10749ca70: _do_watch_progress('/var/folders/yz/pntm5xh11mjb3ckzvf10ql180000gn/T/, <gevent._socket3.socket object, fd=8, family=1, ty, <function show_progress.<locals>.handler at 0x1076)> failed with AssertionError
```

**Comment by aronnem** [comment]
I found this from a web search, since you had the same error I saw. I think the problem may actually be in tqdm: https://github.com/tqdm/tqdm/issues/859
